Added toast.
izothep-projects/projects-test pull request #145
Opened 2022-08-09 16:12 UTC by bre1470

2022-08-09 16:17 UTC, bre1470 commented
Can someone please request a change for the typo?

2022-08-10 14:40 UTC, pawellysy requested changes
TYPO!!!!

2022-08-10 14:40 UTC, pawellysy commented on toast.js
> +console.log('taostscript');
TYPO!

2022-08-11 08:23 UTC, pawellysy approved these changes

2022-08-11 09:43 UTC, merged

2022-08-11 09:46 UTC, bre1470 commented
@pawellysy Thank you! Milestone assignment works. 👍